language: node_js
node_js:
- '0.12'
sudo: false
install:
- cd website
- npm install
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: MPY+2enFH/YxbHn+JzdE5maJk7G6HYYmqWcrMu41wAmS3SyRKxyhy/0KoWL6A/QTXCSZIuSG28jM9YoyGUZm2eeoG5GsWWFhONv9dKif+mlbLvOcBsmPADr0pQXb5VfCYVSAfGo7ErJsF1+PVjG5bR3HZ8tYKeWkJhpqWUenPXauF9yxvZ3t0IxZx+Kt2K+W7k0HQmrS6Z0Vqw3snJ9I8ILj1LJZq1cAiTrrac/8jaTyRtQkflCFVFFZCxTjkHr/y4KhIfNowNbbWLTqyXvWJj7x+w0qI/CsAoNWiuQv7diblWQxKRH0VxG+T7qQT8jxR2RfrYAqa8257sMzYiVbT83yclawb//V18uwZWwetr6KMUdsDr6xgyM6j4qCfWeDpL9d3/+M2wtm0AV2XpTrhF2iCrz2u2Tm9bFy6tvyDPgKA2BJc2eZwFeERB+3nQWJFQ74UBbfzOf6ROwt43aR+JJRFpUGbd0vq3NRKGIhcByuYWt8Sl5wNXana4R75vdZ6gq0pox4D/SGqBzVbSwVOrKENJidzvlk3sGmVGV8Z0oYfSNvZUHDUJ/Biy8wifQus/2QHUMD7XsG5sDooVWyZSlCL9LoEBPbzXqRakAMcZ6iHZWuexnbZUOoj3zQ0fGlgWMj1Bfwkr7jwn5MGwulNToFugO8a4GYv/WvNkFoHko=
